services:
  app:
    image: ghcr.io/soxfor/qbittorrent-natmap:latest
    container_name: qbittorrent-natmap
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Etc/UTC
      - QBITTORRENT_SERVER=ip.a.dd.r
      # - QBITTORRENT_PORT=   # Defaults to 8080
      # - QBITTORRENT_USER=   # Defaults to admin
      # - QBITTORRENT_PASS=   # Defaults to adminadmin
      # - VPN_CT_NAME=        # Defaults to gluetun
      - VPN_GATEWAY=ip.a.dd.r
      # - VPN_IF_NAME=        # Defaults to tun0
      # - CHECK_INTERVAL=     # Defaults to 300sec
      # - NAT_LEASE_LIFETIME= # Defaults to 300sec
    network_mode: "container:gluetun" # Specify the VPN container name here
